language: elixir
elixir:
  - 1.7
  - 1.8
  - 1.9
  - 1.10
otp_release:
  - 21.0
  - 22.0
  - 23.0
exclude:
  - elixir: 1.7
    otp_release: 23.0
  - elixir: 1.8
    otp_release: 23.0
script: 
  - mix format --check-formatted
  - mix test
  - mix dialyzer --halt-exit-status